export const LIQUID_CONFIG = {
  // CAN
  CAN_FOLLOW_STRENGTH: 0.18,
  CAN_SMOOTHNESS: 0.08,
  CAN_MAX_ROTATION: 0.12,
  CAN_MAX_X: 1.5,
  CAN_MAX_Y: 0.8,

  // LIQUID
  LIQUID_STRENGTH: 0.8,
  LIQUID_RADIUS: 0.24,
  LIQUID_DECAY: 0.94,
  LIQUID_VELOCITY_RESPONSE: 1.5,

  RIPPLE_DURATION: 1.4,
  RIPPLE_DAMPING: 0.92,

  // PERFORMANCE
  MAX_DPR: 1.5,
};